### ISSUE TITLE
Error date string could not be parsed al abrir archivo .osm en JOSM

### ISSUE THREAD

**Issue by rodrigorega** [AnderPijoan/cat2osm2#12]
Hola.
Al abrir desde JOSM un archivo .osm generado con Cat2Osm2 obtengo el siguiente mensaje de error:

![image](https://cloud.githubusercontent.com/assets/3441785/13732124/4951c06c-e97b-11e5-9ff9-91ea1437d239.png)

En consola obtengo esto:
> INFO: Open file: /home/user/Descargas/final-68326-.osm (31711 bytes)
> ERROR: org.openstreetmap.josm.io.IllegalDataException: org.openstreetmap.josm.tools.UncheckedParseException: The date string (2016-03-13 15:34:52.911) could not be parsed.. Cause: org.openstreetmap.josm.tools.UncheckedParseException: The date string (2016-03-13 15:34:52.911) could not be parsed.
> org.openstreetmap.josm.io.IllegalDataException: org.openstreetmap.josm.tools.UncheckedParseException: The date string (2016-03-13 15:34:52.911) could not be parsed.
>         at org.openstreetmap.josm.io.OsmReader.doParseDataSet(OsmReader.java:654)
>         at org.openstreetmap.josm.io.OsmReader.parseDataSet(OsmReader.java:672)
>         at org.openstreetmap.josm.io.OsmImporter.parseDataSet(OsmImporter.java:132)
>         at org.openstreetmap.josm.io.OsmImporter.loadLayer(OsmImporter.java:122)
>         at org.openstreetmap.josm.io.OsmImporter.importData(OsmImporter.java:91)
>         at org.openstreetmap.josm.io.OsmImporter.importData(OsmImporter.java:76)
>         at org.openstreetmap.josm.io.FileImporter.importDataHandleExceptions(FileImporter.java:91)
>         at org.openstreetmap.josm.actions.OpenFileAction$OpenFileTask.importData(OpenFileAction.java:364)
>         at org.openstreetmap.josm.actions.OpenFileAction$OpenFileTask.realRun(OpenFileAction.java:317)
>         at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:93)
>         at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:161)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:262)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>         at java.lang.Thread.run(Thread.java:745)
> Caused by: org.openstreetmap.josm.tools.UncheckedParseException: The date string (2016-03-13 15:34:52.911) could not be parsed.
>         at org.openstreetmap.josm.tools.date.DateUtils.tsFromString(DateUtils.java:139)
>         at org.openstreetmap.josm.io.OsmReader.readCommon(OsmReader.java:457)
>         at org.openstreetmap.josm.io.OsmReader.parseNode(OsmReader.java:213)
>         at org.openstreetmap.josm.io.OsmReader.parseOsm(OsmReader.java:158)
>         at org.openstreetmap.josm.io.OsmReader.parseRoot(OsmReader.java:120)
>         at org.openstreetmap.josm.io.OsmReader.parse(OsmReader.java:106)
>         at org.openstreetmap.josm.io.OsmReader.doParseDataSet(OsmReader.java:621)
>         ... 15 more

Info de sistema:

> $ java -jar josm-latest.jar --version
> JOSM/1.5 (9979 es) Linux Debian GNU/Linux 8.3 (jessie)
> $ java -jar cat2osm2.jar -v
> Cat2Osm2 versión 2014-10-14.
> 

También me consta que pasa el mismo problema en Windows. Parece que alguna actualización de JOSM ha roto la compatibilidad con Cat2Osm2, no podría detallar en qué versión o fecha concreta ha pasado esto.

Un saludo.

**Comment by rodrigorega** [comment]
Cierro, ya que publiqué dos veces el mismo ticket.
